site_name: 自主移动机器人使用文档
# site_name_en: Autonomous Mobile Robot Documentation
# site_url: https://mydomain.org/mysite
theme:
  name: material

  features:
    - navigation.tabs       # 顶部标签栏
    - navigation.sections   # 左侧菜单显示“分组标题”
    - navigation.top        # 右下角“回到顶部”按钮
    - search.suggest        # 搜索联想（输入时自动提示)
    - search.highlight      # 搜索结果高亮关键词

  language: zh # 默认语言


  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式


nav:
  - 首页: index.zh.md

  - 快速上手:
      - 设备检查与启动: 01-quick-start/01-device-check.md
      - 连接到机器人: 01-quick-start/02-connect-robot.md
      - 基本功能检测: 01-quick-start/03-basic-function-test.md

  - 机械结构与传感器:
      - 整机结构概述: 02-hardware/01-mechanical-overview.md
      - 运动底盘: 02-hardware/02-mobile-base.md
      - OMS执行机构: 02-hardware/03-oms-actuator.md
      - 传感器外设: 02-hardware/04-sensors.md

  - 软件与开发环境:
      - 环境准备: 03-software/00-preparation.zh.md
      - 安装 Ubuntu: 03-software/01-install-ubuntu.zh.md
      - 安装 ROS 2: 03-software/02-install-ros2.zh.md
      - 安装 VS Code: 03-software/03-install-vscode.zh.md
      - Python 依赖: 03-software/04-install-python-deps.zh.md
      - Docker & NVIDIA: 03-software/05-install-docker-nvidia.zh.md

  - 基础教学:
      - Python 基础: 04-basics/python-basics.md
      - ROS 2 基础: 04-basics/ros2-basics.md

  - 设备硬件参数适配:
      - VMXPi Titan 参数: 05-device-params/01-vmxpi-titan-params.md
      - 底盘运动学参数: 05-device-params/02-chassis-kinematics.md
      - OMS 电机参数: 05-device-params/03-oms-motor-params.md
      - Lidar 驱动参数: 05-device-params/04-lidar-driver-params.md
      - IMU 标定: 05-device-params/05-imu-calibration.md
      - Wi-Fi 参数: 05-device-params/06-wifi-config.md


extra:
  generator: false  #页脚显示“MkDocs制造”
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/489593500?spm_id_from=333.1007.0.0




markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences